---
- name: 'Baixa o aquivo de instalação do Wordpress'
  get_url:
    url: 'https://wordpress.org/wordpress-5.0.tar.gz'
    dest: '/tmp/wordpress.tar.gz'

- name: 'Descompacta o wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: '/var/www/'
    remote_src: yes
  become: yes

- name: Copy a "sudoers" file on the remote machine for editing
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes

- name: 'Configura ip config com as entradas do banco de dados'
  template:
    src: "templates/wp-config.php.j2"
    dest: "{{ wp_installation_dir }}/wp-config.php"
  become: yes

- name: 'Configura Apache para servir Wordpress'
  template:
    src: 'templates/000-default.conf.j2'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes